sudo: required
dist: trusty

services:
  - docker

before_install:
  - sudo apt-get -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" install -y docker-engine
  - sudo service docker restart
  - sudo pip install docker-compose
  - docker-compose up -d db

script:
  - docker-compose up webtest